add_executable(kalles-fraktaler
    CDecNumber.cpp
    CDecNumber.h
    CFixedFloat.cpp
    CFixedFloat.h
    check_for_update.cpp
    check_for_update.h
    cmdline.cpp
    cmdline.h
    double_perturbation.cpp
    double_reference.cpp
    exr.cpp
    exr.h
    floatexp_approximation.cpp
    floatexp_perturbation.cpp
    floatexp_reference.cpp
    fraktal_sft.cpp
    fraktal_sft.h
    gradient.cpp
    gradient.h
    hybrid.cpp
    hybrid.h
    jpeg.cpp
    jpeg.h
    listbox.cpp
    listbox.h
    long_double_perturbation.cpp
    long_double_reference.cpp
    main.cpp
    main.h
    main_bailout.cpp
    main_bailout.h
    main_color.cpp
    main_color.h
    main_examine.cpp
    main_examine.h
    main_formula.cpp
    main_formula.h
    main_information.cpp
    main_information.h
    main_position.cpp
    main_position.h
    main_ptsatuning.cpp
    main_ptsatuning.h
    main_transformation.cpp
    main_transformation.h
    nanomb1_perturbation.cpp
    nanomb1_reference.cpp
    nanomb2_perturbation.cpp
    nanomb2_reference.cpp
    newton.cpp
    newton.h
    opengl.cpp
    opengl.h
    Parameter.cpp
    png.cpp
    png.h
    render.cpp
    scale_bitmap.cpp
    scale_bitmap.h
    Settings.cpp
    Settings.h
    tiff.cpp
    tiff.h
    tooltip.cpp
    tooltip.h
    colour.h
    complex.h
    dual.h
    fifo.h
    floatexp.h
    itercount_array.h
    nanomb1.h
    nanomb1.inc
    nanomb2.h
    nanomb2.inc
    resource.h

#    cursor1.cur
#    fraktal_sft.rc
#    icon.ico
#    icon1.ico
)
